
---
title: "Wild git collaboration practice!"
author: "your names here!"
date: "1/25/2022"
output: html_document
---

```{r setup, include=TRUE, message = FALSE, warning = FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

## STEP 5: No merge conflicts!

```{r partner 1}
### In this code chunk, start with the diamonds dataset (built in to
### ggplot2 package) and create a plot of price vs. carat (or some other
### variables of your choice)

ggplot(data = diamonds, aes(x = carat, y = price)) +
  geom_point(color = "blue")

```

```{r partner 2}
### In this code chunk, start with the diamonds dataset (built in to
### ggplot2 package) and create a subset based on filtering, e.g., 
### size greater than 1 carat or cut is "Ideal"


diamond_ideal_cut <- diamonds %>% # Created a diamond subset # added a test note
  filter(cut == "Ideal") # Filtered for "Ideal" cut
```

## STEP 7: Uh oh, merge conflicts!

```{r break-it-1}

### to plot, summarize, calculate something simple using the diamonds
### dataset.

ggplot(data = diamonds, aes(x = carat, y = clarity)) +
  geom_point(color = "blue")
```

## STEP 11: And even more merge conflicts!

```{r break-it-2}
### Both partners - delete this comment, then write some code here
### to plot, summarize, calculate something simple using the diamonds
### dataset.


```